"""Add notifications and mentor approval

Revision ID: 1897b57d4184
Revises: dc7f5feb9aa6
Create Date: 2025-04-08 11:03:54.207186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1897b57d4184'
down_revision = 'dc7f5feb9aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mentor_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('mentor_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mentor_approval_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dept_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dept_review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('college_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('college_review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('principal_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('principal_review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('principal_review_date')
        batch_op.drop_column('principal_remarks')
        batch_op.drop_column('college_review_date')
        batch_op.drop_column('college_remarks')
        batch_op.drop_column('dept_review_date')
        batch_op.drop_column('dept_remarks')
        batch_op.drop_column('mentor_approval_date')
        batch_op.drop_column('mentor_approval')
        batch_op.drop_column('mentor_email')
        batch_op.drop_column('mentor_name')

    # ### end Alembic commands ###
