"""Update application and funding models

Revision ID: 1e4f26753126
Revises: bc8c4bd07bb3
Create Date: 2025-04-08 15:51:07.984585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4f26753126'
down_revision = 'bc8c4bd07bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('team_members',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('mentor_approval_date')
        batch_op.drop_column('mentor_approval')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('mentor_name')
        batch_op.drop_column('mentor_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('mentor_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('mentor_approval', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('mentor_approval_date', sa.DATETIME(), nullable=True))
        batch_op.alter_column('team_members',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
