"""Add application_notifications relationship

Revision ID: 202106a787e3
Revises: a6c5cd8afd1a
Create Date: 2025-04-08 21:57:35.392709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202106a787e3'
down_revision = 'a6c5cd8afd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
