"""Add approval fields to funding application

Revision ID: 6a503569db24
Revises: 1e4f26753126
Create Date: 2025-04-08 15:57:37.426800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a503569db24'
down_revision = '1e4f26753126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dept_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dept_review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('college_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('college_review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('principal_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('principal_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('principal_review_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('principal_review_date')
        batch_op.drop_column('principal_remarks')
        batch_op.drop_column('principal_status')
        batch_op.drop_column('college_review_date')
        batch_op.drop_column('college_remarks')
        batch_op.drop_column('college_status')
        batch_op.drop_column('dept_review_date')
        batch_op.drop_column('dept_remarks')
        batch_op.drop_column('dept_status')

    # ### end Alembic commands ###
