"""Update all relationships to use back_populates

Revision ID: a6c5cd8afd1a
Revises: f07cf208b381
Create Date: 2025-04-08 21:41:30.362173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c5cd8afd1a'
down_revision = 'f07cf208b381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('application_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('application_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
