"""Add FundingApplication model

Revision ID: bc8c4bd07bb3
Revises: d48ad4ff3018
Create Date: 2025-04-08 15:48:08.572615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8c4bd07bb3'
down_revision = 'd48ad4ff3018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('bill_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('dept_remarks')
        batch_op.drop_column('principal_remarks')
        batch_op.drop_column('principal_review_date')
        batch_op.drop_column('college_remarks')
        batch_op.drop_column('required_components')
        batch_op.drop_column('dept_review_date')
        batch_op.drop_column('dept_status')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('college_status')
        batch_op.drop_column('college_review_date')
        batch_op.drop_column('principal_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_review_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('college_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('dept_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('dept_review_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('required_components', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('college_remarks', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('principal_review_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('principal_remarks', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('dept_remarks', sa.TEXT(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('remarks')
        batch_op.drop_column('bill_path')
        batch_op.drop_column('actual_cost')

    # ### end Alembic commands ###
