"""Add approval status columns to purchase_list and utilization_certificate

Revision ID: dc7f5feb9aa6
Revises: 
Create Date: 2025-04-08 10:53:34.201724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7f5feb9aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('principal_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dept_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('college_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('principal_remarks', sa.Text(), nullable=True))
        batch_op.drop_column('remarks')
        batch_op.drop_column('status')

    with op.batch_alter_table('utilization_certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('principal_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dept_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('college_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('principal_remarks', sa.Text(), nullable=True))
        batch_op.drop_column('coordinator_remarks')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilization_certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordinator_remarks', sa.TEXT(), nullable=True))
        batch_op.drop_column('principal_remarks')
        batch_op.drop_column('college_remarks')
        batch_op.drop_column('dept_remarks')
        batch_op.drop_column('principal_status')
        batch_op.drop_column('college_status')
        batch_op.drop_column('dept_status')

    with op.batch_alter_table('purchase_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), nullable=True))
        batch_op.drop_column('principal_remarks')
        batch_op.drop_column('college_remarks')
        batch_op.drop_column('dept_remarks')
        batch_op.drop_column('principal_status')
        batch_op.drop_column('college_status')
        batch_op.drop_column('dept_status')

    # ### end Alembic commands ###
