"""Add enhanced metrics to Application model

Revision ID: f07cf208b381
Revises: 6a503569db24
Create Date: 2025-04-08 21:35:01.933911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07cf208b381'
down_revision = '6a503569db24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_application')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('team_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('innovation_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('technical_complexity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('project_domain', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('implementation_status', sa.String(length=20), nullable=True))
        batch_op.alter_column('application_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('team_members',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.drop_column('required_components')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_components', sa.TEXT(), nullable=False))
        batch_op.alter_column('team_members',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('application_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('implementation_status')
        batch_op.drop_column('project_domain')
        batch_op.drop_column('technical_complexity')
        batch_op.drop_column('innovation_score')
        batch_op.drop_column('completion_percentage')
        batch_op.drop_column('project_duration')
        batch_op.drop_column('team_size')
        batch_op.drop_column('quotation_path')

    op.create_table('funding_application',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dept_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dept_remarks', sa.TEXT(), nullable=True),
    sa.Column('dept_review_date', sa.DATETIME(), nullable=True),
    sa.Column('college_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('college_remarks', sa.TEXT(), nullable=True),
    sa.Column('college_review_date', sa.DATETIME(), nullable=True),
    sa.Column('principal_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('principal_remarks', sa.TEXT(), nullable=True),
    sa.Column('principal_review_date', sa.DATETIME(), nullable=True),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('actual_cost', sa.FLOAT(), nullable=False),
    sa.Column('bill_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
